CC = clang
CFLAGS = -Wall
PROGRAM = part1
FILES = $(part1.c fileparser.c gridcopy.c)

all: $(PROGRAM)


$(PROGRAM): $(CC) $(CFLAGS) $(FILES) -o part1

# part1: part1.c 
# 	$(CC) -g part1.c -o part1

clean:
	rm part1